#!/bin/bash
rpm -ivh http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm
yum install -y --enablerepo=zabbix zabbix-agent
sed -i.orig -e "s/Server=localhost/Server=zabbix-server/" /etc/zabbix/zabbix_agentd.conf
HOSTNAME=`curl http://169.254.169.254/latest/meta-data/public-hostname`
echo "Hostname=$HOSTNAME" >> /etc/zabbix/zabbix_agentd.conf
service zabbix-agent start
